
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:taskflowapp/core/config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: AppConfig.firebaseApiKey.isNotEmpty ? AppConfig.firebaseApiKey : 'AIzaSyC_fnPlfIvZWa3sDUsQ3marnC-FA-xHJ3o',
    appId: AppConfig.firebaseAppId.isNotEmpty ? AppConfig.firebaseAppId : '1:235528279534:web:f32bd536733587b35eaaff',
    messagingSenderId: AppConfig.firebaseMessagingSenderId.isNotEmpty ? AppConfig.firebaseMessagingSenderId : '235528279534',
    projectId: AppConfig.firebaseProjectId.isNotEmpty ? AppConfig.firebaseProjectId : 'taskflow-61443',
    authDomain: AppConfig.firebaseAuthDomain.isNotEmpty ? AppConfig.firebaseAuthDomain : 'taskflow-61443.firebaseapp.com',
    storageBucket: AppConfig.firebaseStorageBucket.isNotEmpty ? AppConfig.firebaseStorageBucket : 'taskflow-61443.firebasestorage.app',
    measurementId: AppConfig.firebaseMeasurementId.isNotEmpty ? AppConfig.firebaseMeasurementId : 'G-X4BCT73RB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxYNHQKDoqbgKEO_9JZJD51pYzRcaMp4',
    appId: '1:235528279534:android:3bc6a9478c4095b55eaaff',
    messagingSenderId: '235528279534',
    projectId: 'taskflow-61443',
    storageBucket: 'taskflow-61443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhzlNFK2Pg3Q2tMQ38o2xRklJSQIOVLM',
    appId: '1:235528279534:ios:bdd3bb1e20e717c25eaaff',
    messagingSenderId: '235528279534',
    projectId: 'taskflow-61443',
    storageBucket: 'taskflow-61443.firebasestorage.app',
    iosBundleId: 'com.example.taskflowapp',
  );
}
