// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:taskflowapp/core/offline/offline_request_hive.dart';
import 'package:taskflowapp/features/categories/local/model/category_hive/category_hive.dart';
import 'package:taskflowapp/features/profile/data/datasources/local/model/user_details_hive.dart';
import 'package:taskflowapp/features/tasks/local/model/task_hive/task_hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryHiveAdapter());
    registerAdapter(OfflineRequestHiveAdapter());
    registerAdapter(TaskHiveAdapter());
    registerAdapter(UserDetailsHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryHiveAdapter());
    registerAdapter(OfflineRequestHiveAdapter());
    registerAdapter(TaskHiveAdapter());
    registerAdapter(UserDetailsHiveAdapter());
  }
}
